### ISSUE TITLE
Redirect request in gulpfile.js

### ISSUE THREAD

**Issue by emmbertelen** [potree/potree#1013]
I have deployed Potree, and hosting the service with Nginx. I would like to access Potree in `IP/potree` address. So I guess I need to rediect the requests coming from Nginx in gulpfile.js, by modifying this part: 
```
gulp.task('webserver', gulp.series(async function() {
        server = connect.server({
                port: 1234,
                https: false,
        });
}));
```
I have tried to add `middleware` service like this:
```
gulp.task('webserver', gulp.series(async function() {
        server = connect.server({
                port: 1234,
                https: false,
                root: ['.'],
                middleware: async  function(connect, opt) {
                        return [
                                proxy('/potree', {
                                        target: 'http://localhost:1234',
                                        changeOrigin:true,
                                        ws: true      // <-- set it to 'true' to proxy WebSockets
                })
            ]
        }
        });
}));

```
But when I restarted `npm`, it failed:

```
[13:59:58] Using gulpfile ~/potree/gulpfile.js
[13:59:58] Starting 'watch'...
[13:59:58] Starting 'build'...
[13:59:58] Starting 'pack'...
[13:59:58] Starting 'webserver'...
[13:59:58] Starting '<anonymous>'...
[13:59:58] Starting '<anonymous>'...
[13:59:58] Starting 'workers'...
[13:59:58] Starting 'lazylibs'...
[13:59:58] Starting 'shaders'...
[13:59:58] Starting 'icons_viewer'...
[13:59:58] Starting 'examples_page'...
[13:59:58] Starting server...
[13:59:58] Finished 'workers' after 33 ms
[13:59:58] Finished 'lazylibs' after 39 ms
[13:59:59] Finished 'pack' after 75 ms
[13:59:59] Finished '<anonymous>' after 75 ms
[13:59:59] '<anonymous>' errored after 68 ms
[13:59:59] TypeError: steps.push is not a function
    at /home/azureuser/potree/node_modules/gulp-connect/index.js:204:22
    at Array.forEach (<anonymous>)
    at ConnectApp.handlers (/home/azureuser/potree/node_modules/gulp-connect/index.js:203:17)
    at ConnectApp.run (/home/azureuser/potree/node_modules/gulp-connect/index.js:68:10)
    at new ConnectApp (/home/azureuser/potree/node_modules/gulp-connect/index.js:57:10)
    at Object.server (/home/azureuser/potree/node_modules/gulp-connect/index.js:268:11)
    at /home/azureuser/potree/gulpfile.js:80:19
    at bound (node:domain:416:15)
    at runBound (node:domain:427:12)
    at asyncRunner (/home/azureuser/potree/node_modules/async-done/index.js:55:18)
[13:59:59] 'webserver' errored after 76 ms
[13:59:59] 'watch' errored after 78 ms
[13:59:59] The following tasks did not complete: build, <parallel>, shaders, icons_viewer, examples_page
[13:59:59] Did you forget to signal async completion?
```

I did not touch the build task, or anything else. Can anyone please help me how to do this redirection?

**Comment by HeadLessHUN** [comment]
if you hosted with nginx then you dont need npm or any other tools on the server... its just a development sevrer and build tool which assemble the potree.js from modul files and etc...

And why don't you just deploy a stable release which is containing only the requierd files just throw them into the root of the webserver add your pointclouds and index page(s) to the root. and thats all.
