### ISSUE TITLE
How to calcute the course/pitch/roll of 360 image using quaternion?

### ISSUE THREAD

**Issue by dajiang31835008** [potree/potree#1048]
I have some 360 images and pano-poses.csv file ,which is generated by NavVis LX  indoor mobile mapping system. In a pano-poses.csv  file,the 360 image orientation was descirbed by quaternion(pano_ori_w;  pano_ori_x;  pano_ori_y;  pano_ori_z). How to calcute the course/pitch/roll of 360 image using quaternion? I had tried convert quaternion to euler(Z-Y-X order) using "https://www.andre-gaschler.com/rotationconverter/",but there is an error between the panorama and the point cloud.

**Comment by HeadLessHUN** [comment]
i think it would be easer to create a different loader threejs support quaternion so you will need to modify the rotation part and the file loading/parsing....

**Comment by HeadLessHUN** [comment]
> i think it would be easer to create a different loader threejs support quaternion so you will need to modify the rotation part and the file loading/parsing....

but if you really want to tho that calculation outside of potree then you will need ZYX order where roll is X pitch is Y course is Z.

this is how it is apllied in potree
```
			{ // orientation
				var {course, pitch, roll} = image360;
				mesh.rotation.set(
					THREE.Math.degToRad(+roll + 90),
					THREE.Math.degToRad(-pitch),
					THREE.Math.degToRad(-course + 90),
					"ZYX"
				);
			}
```

**Comment by dajiang31835008** [comment]
@HeadLessHUN Thanks for your reply !I try it.

**Comment by DaineGaming** [comment]
Had a similar issue with this when going from Cartesian Coordinates to Potree,

Add an extra Token to the end of your Coordinates.txt file (We called it "Real" you could call it "W" or something similar).

Make the following changes to the "ImageLoader" Class (Around line 77549) to read said token,

```
let [filename, time, long, lat, alt, course, pitch, roll, real] = tokens;
time = parseFloat(time);
long = parseFloat(long);
lat = parseFloat(lat);
alt = parseFloat(alt);
course = parseFloat(course);
pitch = parseFloat(pitch);
roll = parseFloat(roll);
real = parseFloat(real);

let image360 = new Image360(file, time, long, lat, alt, course, pitch, roll, real);
```

Then in your Potree.js file make the following changes to the "Image360" Class (Around line 77228) to calculate the course, pitch and roll,

```
class Image360 {

		constructor(file, time, longitude, latitude, altitude, course, pitch, roll, real) {
			this.file = file;
			this.time = time;
			this.longitude = longitude;
			this.latitude = latitude;
			this.altitude = altitude;

			//this.course = course;
			//this.pitch = pitch;
			//this.roll = roll;

			if (real) {
				var quat = new Quaternion(roll, pitch, course, real);

				var q = quat;
				var m = new Matrix4();
				m.makeRotationFromQuaternion(q);

				var axis = [0, 0, 0];
				var angle = 2 * Math.acos(q.w);
				if (1 - (q.w * q.w) < 0.000001) {
					axis[0] = q.x;
					axis[1] = q.y;
					axis[2] = q.z;
				}
				else {
					// http://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToAngle/
					var s = Math.sqrt(1 - (q.w * q.w));
					axis[0] = q.x / s;
					axis[1] = q.y / s;
					axis[2] = q.z / s;
				}

				var eu = new Euler();
				eu.setFromRotationMatrix(m, 'XYZ');

				this.roll = toReal(toAngle(eu.toArray()[0]));
				this.pitch = toReal(toAngle(eu.toArray()[1]));
				this.course = 360 - toReal(toAngle(eu.toArray()[2]));

			}
			else {
				this.course = course;
				this.pitch = pitch;
				this.roll = roll;
			}

			this.mesh = null;
		}
	};
```

And add the below functions to the Potree.js file

```
function toAngle(x) {
		return x * 180 / Math.PI;
	}
	function toReal(x) {
		if (!isNaN(parseFloat(x)) && isFinite(parseFloat(x))) {
			return parseFloat(parseFloat(x).toFixed(7));
		}
		else {
			return x;
		}
	}
```

**Comment by vocalyang** [comment]
@dajiang31835008 Have you solved this problem? I have also encountered this problem

**Comment by Jaumen90** [comment]
Hi, 
I have the same issue with my pointcloud from NavVis Ivion. I converted pc from e57 to LAS by CloudCompare and created the potree viewer using PotreeConverter 1.7. Together with the point cloud I exported panoramas with csv file that contains _id, filename, timestamp, pano_pos_x, pano_pos_y, pano_pos_z, pano_ori_w, pano_ori_x, pano_ori_y, pano_ori_z_. I've rearranged the data from csv so that the _pano_ori_w_ column was moved to the end of the row (the same as _real_ value). The point cloud has a local coordinate system (indoor scanning).

I made changes to the _class Image360_ and _class Images360Loader_. After adding _real_ value at the end of the 
`let image360 = new Image360(file, time, long, lat, alt, course, pitch, roll, real);` all spheres with panoramas dissapears in the potree viewer. Only this row in the code makes this issue. In the browser I've got the error:
_Uncaught (in promise) ReferenceError: Quaternion is not defined  Images360.js:34 
    at new Image360 (Images360.js:34:1)
    at Images360Loader.load (Images360.js:333:19)_

I have no idea what to do to make it work properly. I need to display the panorama view in such way that it coincides correctly with the point cloud (without translation effect).

Does anyone know how to fix it?

Below I put an example of the csv file:

_filename timestamp pano_pos_x pano_pos_y pano_pos_z pano_ori_x pano_ori_y pano_ori_z real
00000-pano.jpg	1677664716.023647	-0.002070	-0.033464	1.003268	0.011347	-0.015650	0.598369	0.800987_

**Comment by anaschammam** [comment]
Hi guys , did you manage to solve this problem, if so ,can you share with us how you solved it.

**Comment by natsumehe** [comment]
> Hi guys , did you manage to solve this problem, if so ,can you share with us how you solved it.

hi boy,do you have a plane to solve it ,if you do ,i need you help !

**Comment by skylinestars** [comment]
@dajiang31835008 Have you solved this problem? I have also encountered this problem
