### ISSUE TITLE
NodeLoader issue: "current" is undefined.

### ISSUE THREAD

**Issue by lcrumbliss** [potree/potree#1078]
Hello,

After converting a point cloud in potree converter 2.1 using the generate page option, and confirming that the page works using potree viewer 1.8 on my development server, I'm having issues once deployed to the production server.  Note that the production server has been serving point clouds converted using v1.6 (both converter and viewer) for a long time.  With point clouds converted using 2.x and v1.8 for viewing, I have always gotten this error in the console:

 failed to load r
OctreeLoader.js:146 TypeError: Cannot read properties of undefined (reading 'nodeType')
    at NodeLoader.parseHierarchy (OctreeLoader.js:179)
    at NodeLoader.loadHierarchy (OctreeLoader.js:257)
    at async NodeLoader.load (OctreeLoader.js:32)
OctreeLoader.js:147 trying again!

The cloud never displays, but the GUI does.  I did noticed that in the network tab of the browser dev tool that it seems to then want to try and download the entire multi-gig hierarchy.bin file.

Also, in the development server, the response header for content-type is "application/octet-stream".  Again, this one works.  In the production server, the content-type is "multipart/byteranges"

**Comment by lcrumbliss** [comment]
FYI, changing the MIME type for bin on the production server to "application/octet-stream" (to match what it was on the development server) didn't change anything.

**Comment by HeadLessHUN** [comment]
have you updated the production server to 1.8 or newer?

1.6 does not have support for the new fileformat...

**Comment by encsbalazs** [comment]
Hello,
I have the same problem, I'am doing the octree file with python(Flask) + PotreeConverter 2.1 when I want to load the it to my html it load the file but  only a black dot is visible,in the console it writes the same error :
failed to load r0003
OctreeLoader.js:146 TypeError: Cannot read properties of undefined (reading 'nodeType')
    at NodeLoader.parseHierarchy (OctreeLoader.js:179)
    at NodeLoader.loadHierarchy (OctreeLoader.js:257)
    at async NodeLoader.load (OctreeLoader.js:32)
![potree_issue](https://user-images.githubusercontent.com/88153906/147937745-a1a27a94-6b8f-475c-8462-4085f307368c.PNG)

**Comment by HeadLessHUN** [comment]
same question what is the potree viewer version?
is it 1.8?

**Comment by encsbalazs** [comment]
yes is it 1.8  :(
![image](https://user-images.githubusercontent.com/88153906/148028799-2edffc36-c4f8-4c0d-823a-3032c5bda6cb.png)

**Comment by encsbalazs** [comment]
Okey. I started all over again and it works. I think i spoiled it. Thanks (Ha jól látom magyar vagy , akkor így is megköszönöm szerintem a viewerem nem 1.8 volt csak  valami összeakadt :) )

**Comment by KeyaWild** [comment]
> ¿Ha actualizado el servidor de producción a 1.8 o más reciente?
> 
> 1.6 no tiene soporte para el nuevo formato de archivo...



Nice to meet you lcrumbliss.
I am trying do a point cloud with potree converter 2.1 and potree version 1.8.
everything works fine, but I get 

failed to load r420445
OctreeLoader.js:146 TypeError: Failed to fetch
    at fetchCallImpl (main.js?attr=PRVnBTshVDywT5ir5rgtcorWK7HXE-y1uNG2_BpwMxSzygO8xu4-JMiNSO6i6WMYbJPECIAtT6WDB3SVqQizbSwbP79xqiT4vvEgutqlma1GopTLfSojyay_aNoSBXBe:2485:21)
    at fetch (main.js?attr=PRVnBTshVDywT5ir5rgtcorWK7HXE-y1uNG2_BpwMxSzygO8xu4-JMiNSO6i6WMYbJPECIAtT6WDB3SVqQizbSwbP79xqiT4vvEgutqlma1GopTLfSojyay_aNoSBXBe:2491:60)
    at NodeLoader.load (OctreeLoader.js:49:26)
    at OctreeGeometryNode.load (OctreeGeometry.js:78:30)
    at updateVisibility (Potree_update_visibility.js:407:23)
    at Object.updatePointClouds (Potree_update_visibility.js:23:15)
    at Viewer.update (viewer.js:1677:24)
    at Viewer.loop (viewer.js:2248:8)
    at onAnimationFrame (three.module.js:24224:35)
    at onAnimationFrame (three.module.js:12673:3)
OctreeLoader.js:147 trying again!


Where I need put the line "application/octet-stream" to resolv this.
Thanks you!

**Comment by becicmic** [comment]
Hello, 

I am trying to set up my first viewer, and I am seeing the same issue. 

failed to load r                 OctreeLoader.js 145

I see the GUI but not the point cloud.

I checked all paths, and they are correct.
Could you suggest the next step for troubleshooting, please?

I am using the following:
PotreeConvertor 2.1.1
Potree 1.8.0
I run local web server on python (python -m http.server)

Troubleshooting edit:
I see the example pointcloud embeded in potree has a different structure than my converted pointcloud

**example:**
data
  |-> r
    |-> r.bin files
cloud.js

**my cloud:**
hierarchy.bin
log.txt
metadata.json
octree,bin

Could that be the issue?
