### ISSUE TITLE
Error when opening 3d model.

### ISSUE THREAD

**Issue by syazoo** [potree/potree#1093]
Device name	Graphics
Processor	Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz   3.50 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Device ID	63730AFC-C073-4096-86F8-9759B0F93ADC
Product ID	00326-10000-00000-AA580
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

NVidia GTX960
Driver Versio: 27.21.14.6611

16GB DDR 1 1333mhz

Rendered 
Created on: 10/20/2021, 11:19:04 AM
Processing Node: node-odm-1 (auto)
Options: ignore-gsd: true, dsm: true, pc-quality: high, dem-resolution: 2.0, orthophoto-resolution: 2.0
Average GSD: 0.18 cm
Area: 21,786.5 m²
Reconstructed Points: 45,360,676
198 Photos

Ortho displays fine. When I choose 3d model, then check texture, and then try to view, the window with the following error appears. I have completed several other projects with no problem at all. In particular, I rendered the same site plan with photos from an earlier date successfully.

TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
    at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
    at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
    at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
    at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
    at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
    at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
    at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:12858:4)

**Comment by sujitknandan** [comment]
I am also facing similar issue sometimes. My graphics details are as follows

  product: CometLake-U GT2 [UHD Graphics]
  Model: "Intel UHD Graphics"
  Vendor: pci 0x8086 "Intel Corporation"
  Device: pci 0x9b41 "UHD Graphics"
  SubVendor: pci 0x1028 "Dell"
  SubDevice: pci 0x09a0 
  Revision: 0x02
  Driver: "i915"

Any other information required please revert
