### ISSUE TITLE
How to remove current and reload new point cloud in the same scene

### ISSUE THREAD

**Issue by tomvanderputte** [potree/potree#1147]
I'm trying to to remove a current point cloud out of the scene and doing a new call of LoadPointCloud to load a new one, when a certain link is clicked.

I just replicated the LoadPointCloud call but added a pop() on  the viewer.scene.pointclouds in order to remove the current one, otherwise they are both shown.

```
<a href="" id="testlink1" src="./pointclouds/11lmb/metadata.json" name="11LMB" >11LMB</a>
<script>
	$('#testlink1').click(function(){ 		// Load and add point cloud to scene
			Potree.loadPointCloud("./pointclouds/11lmb/metadata.json", "11 LMB", e => {
			let scene = viewer.scene;
			
			//Remove current point cloud
			viewer.scene.pointclouds.pop();
			let pointcloud = e.pointcloud;
			
			let material = pointcloud.material;
			material.size = 1;
			material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
			material.shape = Potree.PointShape.CIRCLE;	
		
			scene.addPointCloud(pointcloud);
			
			viewer.fitToScreen();
			viewer.setEDLEnabled(true);

		});
		return false; });		
</script>
```	

That works for a bit but after a bit of panning Potree crashes:
```
TypeError: Cannot read properties of null (reading 'attributes')
    at Renderer.renderNodes (http://localhost:1234/build/potree/potree.js:63219:17)
    at Renderer.renderOctree (http://localhost:1234/build/potree/potree.js:63793:9)
    at Renderer.render (http://localhost:1234/build/potree/potree.js:63818:10)
    at HQSplatRenderer.render (http://localhost:1234/build/potree/potree.js:70862:22)
    at Viewer.renderDefault (http://localhost:1234/build/potree/potree.js:89861:14)
    at Viewer.render (http://localhost:1234/build/potree/potree.js:89875:11)
    at Viewer.loop (http://localhost:1234/build/potree/potree.js:89999:9)
    at onAnimationFrame (http://localhost:1234/build/potree/potree.js:24409:36)
    at onAnimationFrame (http://localhost:1234/build/potree/potree.js:12858:4)
```

I have a feelling I can't just pop the point cloud of the pointclouds array, but found no method to remove it more cleanly. Any suggestions?

--EDIT:
I've also tried removing the referenceFrame using:
`viewer.scene.referenceFrame.remove(viewer.scene.referenceFrame.getObjectByName(''));` 
But this does nothing, the referenceframe is not removed. 
It might seem weird with the empty name, but the frame does not have a name, and trying this in console just returns the same  Object3D instead of removing it. Even when manually assigning a name to the referenceframe, and then using the getObjectByName, the result remains the same.

**Comment by worlderland** [comment]
Hello @tomvanderputte ,

My team and I have been able to achieve the unmounting of a point cloud by basically mounting an empty scene inside the viewer.
I'll post code snippets below.

Unmount pointcloud button:
`<Tool onClick={() => {
clearViewer(viewer);
setSceneLoaded(null); // Ignore this, it clear the state of our React component
setDrawerOpen(true); // Ignore this, it opens the side drawer where the pointclouds links are of our React component
}}>
<Icon src={process.env.REACT_APP_POTREE_VIEWER_ICONS_PATH + "remove.svg"} alt="" />
</Tool>`

And the clearing function itself:
`const clearViewer = (viewer) => {
let scene = new Potree.Scene();
viewer.setScene(scene);
}`

Though, we are still experiencing what you mention when when hop from pointcloud to pointcloud, as in, we click on a link and we open a pointcloud, then click on another link and open another one, and so forth. Until Potree eventually crashes because it feels like it still keeps all the opened pointclouds somewhere in the background.

**Comment by tomvanderputte** [comment]
Thanks @worlderland,

This seems to work better, but still memory increases with each new loaded point cloud.

I also tried

```
			viewer.scene.scenePointCloud.remove(viewer.scene.pointclouds[0]);
			viewer.scene.pointclouds.pop();
```
and that helped a bit, but still, I think there should be a dedicated function such as scene.removePointcloud. I'll try to find a different approach.

**Comment by worlderland** [comment]
You're welcome @tomvanderputte ...

I agree, we did spend some time reading through the Potree code trying to find some hidden dedicated functions, but we couldn't find any hence why we went with the function above (which is more like a temporary patch that does the job for us).
Luckily our users don't need to switch between pointclouds too often.
I'll keep an eye on this conversation in case you or someone else will come up with a solution.

**Comment by lewibs-Powern** [comment]
@worlderland you mentioned that your potree crashes after a while with pointclouds. At my workplace we seem to have a method for switching between them that has not yet crashed. How long did it take before yours crashed?

**Comment by tomvanderputte** [comment]
Depending on the point clouds, sometimes after two or three times, sometimes after 5 or 10 times.

Opted now for opening a new window without a point cloud, and loading the point cloud with the JSON method. What method are you using

Tom
________________________________

**Comment by lewibs-Powern** [comment]
I found that just adding them all to the scene and toggling their visibility works well. Usually I have 10ish 10gb point clouds with no noticeable speed or memory issues. I think this works due to how potree uses a false sql db for memory help and does not attempt to render or even load anything that is not visible. I have never had the program crash. I think earlier I used to remove them but It crashed so I had to switch since our software is heavily dependent on switching.

lewibs

**Comment by tomvanderputte** [comment]
Ok I'll try that vs akwardly removing them :) thanks!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lewibs-Powern** [comment]
unrelated. But by chance have you guys added a mesh to the scene? and how did you deal with the alignment issue? 
my post asking about it: #1278

**Comment by tomvanderputte** [comment]
Nope sorry

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AlucardLO** [comment]
I'm running into this issue as well. I can seem to unload all the Point Cloud data.

Related #507

**Comment by worlderland** [comment]
> unrelated. But by chance have you guys added a mesh to the scene? and how did you deal with the alignment issue? my post asking about it: #1278

Hi @lewibs-Powern 
Do you mean something like this?
![image](https://user-images.githubusercontent.com/42766911/220254807-edb97b11-431e-4766-8892-9237d560203a.png)

It's hard to explain, our model perfectly aligns with the cloud because every scan has the same 0, 0, 0 coordinates which were used by the designers to create the model.
BTW, we only had success with .obj files and we're still working on other formats (i.e. .stl).

**Comment by worlderland** [comment]
> I'm running into this issue as well. I can seem to unload all the Point Cloud data.
> 
> Related #507

Hi @AlucardLO ,

I will double check with my superiors if I'm allowed to share the code and will let you know. I believe we have achieved the unloading of the cloud.

**Comment by AlucardLO** [comment]
Hi @worlderland 

Currently I'm just doing the following:

` while (this.viewer.scene.pointclouds.length > 0) {
this.viewer.scene.scenePointCloud.children.splice(this.viewer.scene.scenePointCloud.children.indexOf(this.viewer.scene.pointclouds[0]), 1,);
this.viewer.scene.pointclouds.splice(0, 1);
  }`

Although this is @tomvanderputte solution...

**Comment by lewibs** [comment]
@worlderland yep that's exactly what I mean. Which version of potree are you using? Our components used to align but no longer do after we updated.

**Comment by worlderland** [comment]
> @worlderland yep that's exactly what I mean. Which version of potree are you using? Our components used to align but no longer do after we updated.

@lewibs I'm not sure about the Potree version as we have butched its code to suit our needs (and to fix some of its bugs too), but here is the code we use to load the models:

`const loadModels = async (models) => {

        await models.forEach(async (model) => {

            eventEmitter.emit('onStartLoad', { uniqueId: model.id, name: model.name, percentComplete: 0 });

            let loader = new Potree.OBJLoader();

            let self = this;

            if (viewerRef.scene.scene.children.find(object => object.eprId === model.id) !== undefined)
                return;

            let onProgress = function (xhr) {
                if (xhr.lengthComputable) {
                    let percentComplete = (xhr.loaded / xhr.total) * 100;

                    eventEmitter.emit('onLoadProgress', { uniqueId: model.id, percentComplete, name: model.name });
                    // self.onLoadProgress(percentComplete);
                }
            };

            let onError = function (xhr) {
                if (process.env.NODE_ENV === 'development') {
                    console.log(chalk.cyan(`onError xhr: ${xhr}`))
                }
            };

            loader.load(await getSignedUrl(`${scanWorldDetails.id}/${model.file.path}`), function (object) {
                object.eprId = model.id;
                // loader.load(`${Potree.resourcePath}/models/MC-AGIG22-007-01_Rev_II_GS_021222.obj`, function ( object ) {
                // loader.load(`${Potree.resourcePath}/models/stanford_bunny_reduced.obj`, function ( object ) {

                object.traverse(function (child) {
                    if (child instanceof Potree.Mesh) {
                        // child.material.map = texture;
                        child.material.transparent = true;
                        child.material.color.setHex(0x00FF00); // lime
                        child.material.opacity = 1; // lime
                    }
                });

                object.position.set(model.position.x, model.position.y, model.position.z);
                object.rotation.set(model.rotation.x, model.rotation.y, model.rotation.z);
                object.scale.set(model.scale.x, model.scale.y, model.scale.z);
                // object.position.set(142.88, 84.57, 86.47);
                // object.position.set(589871.587, 231528.213, 725.634);
                // object.scale.multiplyScalar(0.001);
                // object.rotation.set(Math.PI / 2, Math.PI, 0)

                const edges = new Potree.EdgesGeometry(object.children[0].geometry);
                const line = new Potree.LineSegments(edges, new Potree.LineBasicMaterial({ color: 0x000000, transparent: true, opacity: 0.25 }));
                line.scale.multiplyScalar(0.001);
                line.lineWidth = 0.2;

                viewerRef.scene.scene.add(object);
                viewerRef.scene.scene.add(line);

                eventEmitter.emit('onFinishLoad', { uniqueId: model.id}) ;
                // self.onFinishLoad(model.id);

            }, onProgress, onError);
        })

    }`

Please ignore the getSignedUrl as it's an Azure function... We're serving the point clouds privately from Azure.

What I can also tell you is that the alignment problem could be due to a different coordinates system or 0 0 0 point between the scanner and the design platform (i.e. CAD or Solidworks). We had the same issue but after we spoke to our survey and design team, they matched the coordinates and we didn't have anymore problems.

Also, have a play with the scaling (line.scale.multiplyScalar()), because we had to set it to 0.001, yours might be different.

**Comment by disi-koa** [comment]
Hi @worlderland, any update on if you are able to share the solution for unloading point clouds? Thanks.

**Comment by disarticulate** [comment]
looks like to remove point clouds:
```
//remove pointclouds
for (const pointcloud of scene.pointclouds) {
  scene.scenePointCloud.remove(p)
}
scene.pointclouds.length = 0
```
to remove point clouds in gui tree:
```
   let pcChild = $(`#pointclouds`).children('ul').children('[role=treeitem]')
   pcChild.each(function() { $('#pointclouds').jstree('delete_node', this.id) })
```
would be great to add a removePointcloud as:
```
addPointCloud(pointcloud) {
      const index = this.scene.pointclouds.indexOf(pointcloud)
      if (index > -1) {
        this.scene.pointclouds.splice(index, 1)
	this.scenePointCloud.remove(pointcloud)
	this.dispatchEvent({
		type: 'pointcloud_removed',
		pointcloud: pointcloud
	})
     }
}
```
the trouble is then how to get the ui to respond. the node id does not correspond to anything, so it's a big cudgle
