### ISSUE TITLE
Error while npm -v 

### ISSUE THREAD

**Issue by ruchika-2210** [potree/potree#1169]
while running the command ""npm -v error is occurring.

evalmachine.<anonymous>:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:47:5
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Admin\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)

Node.js v17.7.1

1.Installed node js and also installed the  4-5 versions multiple times.
Searched Google , but there is no solution.
Very urgent!!!

**Comment by NenadTrifunovic** [comment]
Have the same problem
