### ISSUE TITLE
Potree encountered error when trying to view a 3d textured model

### ISSUE THREAD

**Issue by martinr36** [potree/potree#1241]
When trying to view a specific 3D model, when trying to view the textured model it starts to render, then all of a sudden i get the following message:

TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
    at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
    at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
    at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
    at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
    at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
    at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
    at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:12858:4)

This is using the windows native version of WebODM on the following laptop:

Chassis & Display Cosmos Series: 15.6" Matte Full HD 144Hz 45% NTSC LED Widescreen (1920x1080)
Processor (CPU) Intel® Core™ i7 Six Core Processor 10750H (2.6GHz, 5GHz Turbo)
Memory (RAM) 16GB Corsair 2666MHz SODIMM DDR4 (2 x 8GB)
Graphics Card NVIDIA® GeForce® GTX 1650 Ti - 4.0GB GDDR5 Video RAM - DirectX® 12.1

While observing task manager, it seems as though only the intergrated graphics is being used  (100% utilisation), and no use of the GTX1650 Ti

OS is W11 22H2 (fully up to date)

Other 3D textured models open fine

**Comment by martinr36** [comment]
So I reported this over a fortnight ago, and no reaction whatsoever
