### ISSUE TITLE
Potree Encounted an Error - Failed to execute 'bindAttribLocation'

### ISSUE THREAD

**Issue by Spontaz** [potree/potree#1341]
Using WebODM. I get Potree Encountered an Error when I add texture to the 3D model.

Running 13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz, 64 GB ram
ROG Strix Z790-F Gaming WIFI, Intel® Z790 Chipset, LGA 1700, ATX Motherboard
GeForce RTX™ 3060 12GB VERTO™, 1320 - 1777MHz, 12GB GDDR6
FireFox 115.0.1 (64-bit)
Windows 11 Home Version 22H2 build 22621.1848

TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at WebGLRenderingContext.bindAttribLocation ()
    at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
    at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
    at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
    at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
    at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
    at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
    at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
    at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)

**Comment by KlaRu63** [comment]
I got the same Error on using WebODM on showing 3D model

Prozessor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installierter RAM	32,0 GB (27,9 GB verwendbar)
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
GeForce RTX 3070 8GB
Windows 11 PRO Vers. 22H2
FireFox 114.0.2

TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at WebGLRenderingContext.bindAttribLocation ()
    at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
    at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
    at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
    at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
    at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
    at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
    at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
    at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)
