### ISSUE TITLE
WebODM crashes when trying to view textured 3D model

### ISSUE THREAD

**Issue by benji2182** [potree/potree#1366]
I was trying to model a jobsite, got 1340 images, completed in nearly 12hrs of processing.
Point cloud and measurements working fine, but when I try to toggle Texture view the program crashes and giving me an error.  Below is the error, system specs, project details, WebGL report.

Error:
TypeError: Failed to execute 'bindAttribLocation' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLProgram'.
    at WebGLRenderingContext.bindAttribLocation ()
    at Shader.linkProgram (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62614:9)
    at Shader.update (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:62564:9)
    at Renderer.renderOctree (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63529:13)
    at Renderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:63840:10)
    at PotreeRenderer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:70348:21)
    at Viewer.renderDefault (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89890:14)
    at Viewer.render (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:89904:11)
    at Viewer.loop (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:90028:9)
    at onAnimationFrame (http://127.0.0.1:29800/static/app/js/vendor/potree/build/potree/potree.js:24409:36)

PC Specs: 
12900k, 3090Ti, Aorus z690 Pro, 64GB DDR5-5600, Samsung 980 NVME 2TB.

Project Details:
1340 Images, processed and completed in 11:53:16 
Processing Node: | node-odm-1 (manual)
Options: | auto-boundary: true, dsm: true, pc-quality: high, dem-resolution: 2.0, orthophoto-resolution: 2.0
Average GSD: | 0.73 cm
Area: | 79,161.04 m²
Reconstructed Points: | 267,446,901
Disk Usage: | 16.24 Gb

WebGL: ✓ This browser supports WebGL 1 & 2
Platform: | Win32
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) WebODM/1.0.0 Chrome/80.0.3987.163 Electron/8.5.5 Safari/537.36
webgl
WebGL 1.0 (OpenGL ES 2.0 Chromium)
WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
WebKit
WebKit WebGL
Google Inc.
ANGLE (NVIDIA GeForce RTX 3090 Ti Direct3D11 vs_5_0 ps_5_0)
Available
Yes, D3D9
No

**Comment by pierotofy** [comment]
This is not an issue with Potree, but rather with WebODM.
