### ISSUE TITLE
Error when setting profileWindowController threshold to 50,000

### ISSUE THREAD

**Issue by corymsmith** [potree/potree#400]
When I increase the profileWindowController threshold via:

`viewer.profileWindowController.threshold = 50000;`

I see the following error eventually when using the profile window, the error is happening here: https://github.com/potree/potree/blob/2662d3d55db9f538d76f5deedc7bcfe6f282947d/src/viewer/profile.js#L451

```
potree.js:16208 Uncaught RangeError: Source is too large
    at Float32Array.set (native)
    at ProfileWindow.addPoints (http://localhost:3030/libs/potree/potree.js:16208:43)
    at ProfileWindowController.progressHandler (http://localhost:3030/libs/potree/potree.js:16438:23)
    at Object.onProgress (http://localhost:3030/libs/potree/potree.js:16475:11)
    at ProfileRequest.update (http://localhost:3030/libs/potree/potree.js:7625:19)
    at Function.Potree.updatePointClouds (http://localhost:3030/libs/potree/potree.js:225:34)
    at PotreeViewer.update (http://localhost:3030/libs/potree/potree.js:15389:24)
    at PotreeViewer.loop (http://localhost:3030/libs/potree/potree.js:15469:8)
```

**Comment by corymsmith** [comment]
I'm not super familiar with the internals, otherwise I would try to fix and put together a PR

**Comment by corymsmith** [comment]
I see that `maxPoints` is set to 50,000: https://github.com/potree/potree/blob/2662d3d55db9f538d76f5deedc7bcfe6f282947d/src/viewer/profile.js#L18 and the position buffer length is calculated using that value so the total length is 150,000: https://github.com/potree/potree/blob/2662d3d55db9f538d76f5deedc7bcfe6f282947d/src/viewer/profile.js#L25

When I get this error `posBuffer` has a length of around 168,000 or so.
