### ISSUE TITLE
WebGL Error while viewer.freeze = true

### ISSUE THREAD

**Issue by rfrenz-avio** [potree/potree#510]
Hi,
I'm trying to improve performance in my application by pausing point loading while the user is not interacting with the viewer (e.g. while a modal dialog is open in front of it).

I'm trying to achieve this by calling Viewer.setFreeze(true) (and back to 'false' once the user is again ready to interact).  It mostly works, but we regularly get the below error after an arbitrary amount of time.  The viewer dom element goes white and prints the following:

> Potree Encountered An Error
> This may happen if your browser or graphics card is not supported. 
> We recommend to use Chrome or Firefox.
> 
> Please also visit webglreport.com and check whether your system supports WebGL.
> 
> If you are already using one of the recommended browsers and WebGL is enabled, consider filing an issue report at github,
> including your operating system, graphics card, browser and browser version, as well as the error message below.
> Please do not report errors on unsupported browsers.
> 
> TypeError: Cannot read property 'attributes' of null
>    at Renderer.createBuffer (http://72.95.138.100:3000/libs/potree/potree.js:1439:38)
>    at Renderer.renderNodes (http://72.95.138.100:3000/libs/potree/potree.js:1704:24)
>    at Renderer.renderOctree (http://72.95.138.100:3000/libs/potree/potree.js:2075:8)
>    at Renderer.render (http://72.95.138.100:3000/libs/potree/potree.js:2099:9)
>    at PotreeRenderer.render (http://72.95.138.100:3000/libs/potree/potree.js:17066:20)
>    at PotreeViewer.render (http://72.95.138.100:3000/libs/potree/potree.js:19892:25)
>    at PotreeViewer.loop (http://72.95.138.100:3000/libs/potree/potree.js:20041:8)

This trace was captured from Potree 1.6 release, from Chrome on Windows 10.

Any idea what's going on, or how to debug?

Thanks,
-Ryan

**Comment by mparhiz** [comment]
Hi, 
I have the same issue on Potree 1.6 when I am loading large LAS file. Any idea?
Thanks
