### ISSUE TITLE
undefined$c

### ISSUE THREAD

**Issue by xiaqingp** [potree/potree#528]
After I build and run gulp watch, I go to http://localhost:1234/examples/viewer.html

An error shows that 

ReferenceError: undefined$c is not defined
    at Annotation.collapseThreshold.find.e (http://localhost:8000/build/potree/potree.js:2918:20)
    at Array.find ()
    at new Annotation (http://localhost:8000/build/potree/potree.js:2917:62)
    at new Scene (http://localhost:8000/build/potree/potree.js:16879:24)
    at new Viewer (http://localhost:8000/build/potree/potree.js:24177:21)
    at http://localhost:8000/test_0/web_map_visualizer.html:43:25

Look inside, it seems all "undefined" in Annotation.js is written as "undefined$c" in potree.js in build directory. Could anyone help one this?

Thanks in advance

**Comment by xiaqingp** [comment]
to be more specific, seem all undefined cannot be built, all have different kinds of strange suffix like $la, $17, $c ....

**Comment by eljenso** [comment]
I'm getting the same error.
Just cloned repo and followed instructions in README.

**Comment by eljenso** [comment]
@xiaqingp Got it working by downgrading to node 9.
