### ISSUE TITLE
getting ReferenceError: primordials is not defined when building

### ISSUE THREAD

**Issue by thriskel** [potree/potree#655]
I am trying to build the repo in windows with 

>  gulp watch

but this returns this error: 

```
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\potree\potree-develop\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\potree\potree-develop\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\potree\potree-develop\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
```

**Comment by thriskel** [comment]
I installed the version 4.0.0 of gulp and now it gives the error: 

>AssertionError [ERR_ASSERTION]: Task function must be specified

**Comment by thriskel** [comment]
used gulp@2.7.0 and gives:

> [gulp] Running 'workers'...
> [gulp] Errored 'workers' in 0 ms Invalid or missing glob string
> [gulp] Finished 'workers' in 1 ms

**Comment by Raquel0** [comment]
Hi! ✋ 
I had the same problem and solved it following this steps before gulp watch.

`cd direcotry-to-potree-main-folder>`
`npm install --save`
`npm install -g gulp`
`npm install -g rollup`
**`npm i natives`**
`gulp watch
`

Hope this helps 😄

**Comment by thriskel** [comment]
@Raquel0 I did as you suggested, it didn't work, do you remember what error you had?

**Comment by Raquel0** [comment]
@thriskel Hi!
i don't remember exactly, sorry that i cannot help more with this.

**Comment by Nogbit** [comment]
Node 12 and Gulp 3 aren't compatible https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

Got it to work by downgrading node to 10.16.0 and running the documented commands.

**Comment by Ashish776** [comment]
node 8 used

**Comment by sahil067** [comment]
evalmachine.<anonymous>:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at evalmachine.<anonymous>:35:5
    at Object.<anonymous> (C:\Users\MY_PC\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\MY_PC\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

**Comment by midnight-dev** [comment]
@sahil067 This error doesn't look like it has anything to do with Potree. Make sure you don't have a bad/old version of node or gulp installed. Read some of the other comments. If you're on a Mac, try using Windows. If you installed node a long time ago, try reinstalling node LTS with native support. I'm suggesting this because it appears your stack trace mentions filesystem and native modules at one point. 

If you need further help, consider writing an explanation so there's more information with appropriate context. It's difficult to assist otherwise. Good luck.

**Comment by zhangv** [comment]
try "nvm use 11"
