### ISSUE TITLE
gulp watch not working

### ISSUE THREAD

**Issue by freshcoderchan** [potree/potree#683]
Hi @m-schuetz 
Thanks for your great work.
I am following the steps you wrote in `README.md`
When I run `gulp watch`, I am getting this error now.

```
[02:25:00] 'shaders' errored after 52 ms
[02:25:00] TypeError: Cannot read property 'readFile' of undefined
    at C:\xampp\htdocs\Project\Open-Source\Javascript\potree\gulpfile.js:390:29
    at taskWrapper (C:\xampp\htdocs\Project\Open-Source\Javascript\potree\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (C:\xampp\htdocs\Project\Open-Source\Javascript\potree\node_modules\async-done\index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[02:25:00] 'build' errored after 102 ms
[02:25:00] 'watch' errored after 107 ms
```

I tried to fix but couldn't fix.
Could you please help me to fix?
Thank you.

**Comment by freshcoderchan** [comment]
I have fixed this issue my self.

**Comment by potree** [comment]
Hi, what was the issue and how did you fix it? In case someone else stumbles upon the same problem.

**Comment by freshcoderchan** [comment]
Hi 
My original node version was `8.11.6 `so I updated node version with `10.16.1`
It fixed the above issue but I got a new issue.

```
src/Potree.js → build/potree/potree.js...
[!] Error: Could not resolve '../../build/shaders/shaders.js' from src\materials\EyeDomeLightingMaterial.js
Error: Could not resolve '../../build/shaders/shaders.js' from src\materials\EyeDomeLightingMaterial.js
    at error (C:\Users\Top-Coder\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:9421:30)
    at ModuleLoader.handleMissingImports (C:\Users\Top-Coder\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:16456:17)
    at ModuleLoader.<anonymous> (C:\Users\Top-Coder\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:16507:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Top-Coder\AppData\Roaming\npm\node_modules\rollup\dist\rollup.js:15480:28)


[04:31:36] 'shaders' errored after 1.5 s
[04:31:36] Error: ENOENT: no such file or directory, open './build/shaders/shaders.js'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at C:\xampp\htdocs\Project\Open-Source\Javascript\potree\gulpfile.js:403:5
[04:31:36] 'build' errored after 1.55 s
[04:31:36] 'watch' errored after 1.55 s
```
So I created the **shaders** folder in **build** folder manually so it fixed this issue.
So **gulp watch** is working properly and I am seeing examples now.
Thanks for your great work again. 👍
