### ISSUE TITLE
Error: ENOENT: no such file or directory, open './build/shaders/shaders.js'

### ISSUE THREAD

**Issue by kannes** [potree/potree#693]
Fresh clone on an uptodate Archlinux, following the instructions in README, gave me the same error @freshcoderchan had in https://github.com/potree/potree/issues/683#issuecomment-518197984

```
$ git clone https://github.com/potree/potree
Cloning into 'potree'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 15917 (delta 1), reused 1 (delta 0), pack-reused 15909
Receiving objects: 100% (15917/15917), 115.55 MiB | 21.55 MiB/s, done.
Resolving deltas: 100% (8893/8893), done.

$ cd potree/

$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 440 packages from 263 contributors and audited 6603 packages in 7.832s
found 93 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

$ gulp watch
[17:35:10] Using gulpfile /tmp/potree/gulpfile.js
[17:35:10] Starting 'watch'...
[17:35:10] Starting 'build'...
[17:35:10] Starting 'pack'...
[17:35:10] Starting 'webserver'...
[17:35:10] Starting '<anonymous>'...
[17:35:10] Starting '<anonymous>'...
[17:35:10] Starting 'workers'...
[17:35:10] Starting 'shaders'...
[17:35:10] Starting 'icons_viewer'...
[17:35:10] Starting 'examples_page'...
[17:35:10] Starting server...
[17:35:10] Finished 'workers' after 33 ms
[17:35:10] Finished 'icons_viewer' after 34 ms
[17:35:10] Finished 'examples_page' after 35 ms
[17:35:10] Finished 'pack' after 95 ms
[17:35:10] Finished '<anonymous>' after 95 ms
[17:35:10] Finished '<anonymous>' after 88 ms
[17:35:10] Finished 'webserver' after 96 ms
[17:35:11] Server started http://localhost:1234
[17:35:11] Running server
created examples/page.html
created resources/icons/index.html
[17:35:11] 'shaders' errored after 590 ms
[17:35:11] Error: ENOENT: no such file or directory, open './build/shaders/shaders.js'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1210:35)
    at /tmp/potree/gulpfile.js:403:5
[17:35:11] 'build' errored after 639 ms
[17:35:11] 'watch' errored after 641 ms
```

`mkdir build/shaders` fixed it, `gulp watch` worked successfully after I created that directory.

PS: @potree, please write some proper git summaries, not "...". I meant to check recent commits about this error but decided not to check every undescript commit then...

**Comment by kannes** [comment]
Actually I am not sure I fixed anything at all because running `gulp watch` now still prints a (non-fatal?) error about the shaders.js file:

```
$ gulp watch
[17:39:57] Using gulpfile /tmp/potree/gulpfile.js
[17:39:57] Starting 'watch'...
[17:39:57] Starting 'build'...
[17:39:57] Starting 'pack'...
[17:39:57] Starting 'webserver'...
[17:39:57] Starting '<anonymous>'...
[17:39:57] Starting '<anonymous>'...
[17:39:57] Starting 'workers'...
[17:39:57] Starting 'shaders'...
[17:39:57] Starting 'icons_viewer'...
[17:39:57] Starting 'examples_page'...
[17:39:57] Starting server...
[17:39:57] Finished 'workers' after 71 ms
[17:39:57] Finished 'icons_viewer' after 72 ms
[17:39:57] Finished 'examples_page' after 78 ms
[17:39:57] Finished 'pack' after 134 ms
[17:39:57] Finished '<anonymous>' after 137 ms
[17:39:57] Finished '<anonymous>' after 130 ms
[17:39:57] Finished 'webserver' after 138 ms
[17:39:57] Server started http://localhost:1234
[17:39:57] Running server
created examples/page.html
created resources/icons/index.html


src/Potree.js → build/potree/potree.js...
[!] Error: Could not resolve '../../build/shaders/shaders.js' from src/materials/EyeDomeLightingMaterial.js
Error: Could not resolve '../../build/shaders/shaders.js' from src/materials/EyeDomeLightingMaterial.js
    at error (/usr/lib/node_modules/rollup/dist/rollup.js:9435:30)
    at ModuleLoader.handleMissingImports (/usr/lib/node_modules/rollup/dist/rollup.js:16504:17)
    at ModuleLoader.<anonymous> (/usr/lib/node_modules/rollup/dist/rollup.js:16555:26)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/rollup/dist/rollup.js:40:28)


[17:39:58] Finished 'shaders' after 628 ms
[17:39:58] Starting '<anonymous>'...
[17:39:58] Finished '<anonymous>' after 7.39 ms
[17:39:58] Finished 'build' after 686 ms
[17:39:58] Finished 'watch' after 688 ms

```

**Comment by kannes** [comment]
Thanks, all working fine now :)
